#!/bin/bash

#the test config files only output to the stdout instead of graphite
sudo forever restart stats.js curalateConfig-1-test.js
sudo forever restart stats.js curalateConfig-2-test.js
sudo forever restart stats.js curalateConfig-3-test.js
sudo forever restart proxy.js curalateProxyConfig.js