#!/bin/bash

sudo forever stopall
sudo forever start stats.js curalateConfig-1.js
sudo forever start stats.js curalateConfig-2.js
sudo forever start stats.js curalateConfig-3.js
sudo forever start proxy.js curalateProxyConfig.js
sudo forever list